const commandHandlers = {
  ...require("./authService"),
  ...require("./mfaService"),
  ...require("./fileService"),
  ...require("./commonService"),
  ...require("./userService"),
  ...require("./nhansuService"),
  ...require("./kinhdoanhService"),
  ...require("./muahangService"),
  ...require("./rndService"),
  ...require("./warehouseService"),
  ...require("./lowcodenocodeService"),
  ...require("./kpiService"),
  ...require("./pushService"),
  ...require("./qcService"),
  ...require("./sanxuatService"),
  ...require("./amazonServices"),
  ...require("./aiServices"),
  ...require("./translationDictionaryService"),
  ...require("./subscriptionService"),
  ...require("./columnCommentService"),
  ...require("./schemaAdminService"),
  ...require("./chat/chatRoomService"),
  ...require("./chat/chatFriendService"),
  ...require("./mail/mailAccountService"),
  ...require("./mail/mailService"),
  ...require("./mail/mailSendService"),
};

module.exports = commandHandlers;