/**
 * Migration khởi tạo MODULE EMAIL TẬP TRUNG.
 *
 * Tạo các bảng `ZTB_MAIL_*`:
 *  - ZTB_MAIL_ACCOUNT           — mailbox POP3/SMTP của nhân viên (hoặc dùng chung)
 *  - ZTB_MAIL_MESSAGE           — metadata email (KHÔNG chứa body lớn)
 *  - ZTB_MAIL_RECIPIENT         — người nhận chuẩn hoá (TO/CC/BCC)
 *  - ZTB_MAIL_PHYSICAL_FILE     — kho file vật lý trên NAS (dedup theo SHA-256)
 *  - ZTB_MAIL_ATTACHMENT        — đính kèm của email (trỏ tới file vật lý)
 *  - ZTB_MAIL_USERSTATE         — trạng thái đọc/sao THEO TỪNG USER (mailbox dùng chung)
 *  - ZTB_MAIL_THREAD            — hội thoại (conversation) cho email
 *  - ZTB_MAIL_FOLDER            — thư mục hiển thị phía client (không sync từ server)
 *  - ZTB_MAIL_DRAFT             — bản nháp soạn thảo
 *  - ZTB_MAIL_SYNC_LOG          — nhật ký mỗi lần đồng bộ mailbox
 *  - ZTB_MAIL_SYNC_CHECKPOINT   — con trỏ UIDL + khoá chống chạy chồng
 *
 * Idempotent — chạy lại nhiều lần không lỗi, không ghi đè dữ liệu.
 * Chạy: node scripts/migrate_mail_tables.js
 *
 * ⚠️ Multi-statement DDL dùng `openConnection().query()` (KHÔNG dùng queryDB_New).
 */
const { openConnection } = require("../config/database");

const STATEMENTS = [
  {
    name: "ZTB_MAIL_ACCOUNT",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_ACCOUNT')
BEGIN
  CREATE TABLE ZTB_MAIL_ACCOUNT (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    CTR_CD          NVARCHAR(20)  NOT NULL,
    EMPL_NO         NVARCHAR(20)  NULL,           -- chủ sở hữu; NULL = mailbox dùng chung
    EMAIL_ADDRESS   NVARCHAR(510) NOT NULL,
    DISPLAY_NAME    NVARCHAR(200) NULL,
    POP3_HOST       NVARCHAR(200) NULL,
    POP3_PORT       INT           NULL,
    POP3_SECURE     BIT           NOT NULL CONSTRAINT DF_MAIL_ACC_POP3SEC DEFAULT 1,
    POP3_USERNAME   NVARCHAR(200) NULL,
    POP3_CRED_ENC   NVARCHAR(MAX) NULL,           -- AES-256-GCM (không plaintext)
    SMTP_HOST       NVARCHAR(200) NULL,
    SMTP_PORT       INT           NULL,
    SMTP_SECURE     BIT           NOT NULL CONSTRAINT DF_MAIL_ACC_SMTPSEC DEFAULT 1,
    SMTP_USERNAME   NVARCHAR(200) NULL,
    SMTP_CRED_ENC   NVARCHAR(MAX) NULL,
    IS_ACTIVE       BIT           NOT NULL CONSTRAINT DF_MAIL_ACC_ACTIVE DEFAULT 1,
    IS_SHARED       BIT           NOT NULL CONSTRAINT DF_MAIL_ACC_SHARED DEFAULT 0,
    LAST_SYNC_AT    DATETIME2     NULL,
    LAST_SYNC_STATUS NVARCHAR(30) NULL,
    LAST_ERROR      NVARCHAR(1000) NULL,
    CREATED_AT      DATETIME2     NOT NULL CONSTRAINT DF_MAIL_ACC_CREATED DEFAULT GETDATE(),
    UPDATED_AT      DATETIME2     NOT NULL CONSTRAINT DF_MAIL_ACC_UPDATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_ACCOUNT';
END`,
  },
  {
    name: "UX_MAIL_ACCOUNT_EMAIL",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_MAIL_ACCOUNT_EMAIL')
BEGIN
  CREATE UNIQUE INDEX UX_MAIL_ACCOUNT_EMAIL ON ZTB_MAIL_ACCOUNT (CTR_CD, EMAIL_ADDRESS);
  PRINT 'Created UX_MAIL_ACCOUNT_EMAIL';
END`,
  },
  {
    name: "IX_MAIL_ACCOUNT_SYNC",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_ACCOUNT_SYNC')
BEGIN
  CREATE INDEX IX_MAIL_ACCOUNT_SYNC ON ZTB_MAIL_ACCOUNT (IS_ACTIVE, LAST_SYNC_AT);
  PRINT 'Created IX_MAIL_ACCOUNT_SYNC';
END`,
  },
  {
    name: "ZTB_MAIL_THREAD",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_THREAD')
BEGIN
  CREATE TABLE ZTB_MAIL_THREAD (
    ID               INT IDENTITY(1,1) PRIMARY KEY,
    CTR_CD           NVARCHAR(20)  NULL,
    SUBJECT_NORM     NVARCHAR(400) NULL,
    PARTICIPANT_KEY  NVARCHAR(400) NULL,
    LAST_MESSAGE_AT  DATETIME2     NULL,
    MESSAGE_COUNT    INT           NOT NULL CONSTRAINT DF_MAIL_THREAD_CNT DEFAULT 0,
    CREATED_AT       DATETIME2     NOT NULL CONSTRAINT DF_MAIL_THREAD_CREATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_THREAD';
END`,
  },
  {
    name: "IX_MAIL_THREAD_LAST",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_THREAD_LAST')
BEGIN
  CREATE INDEX IX_MAIL_THREAD_LAST ON ZTB_MAIL_THREAD (CTR_CD, LAST_MESSAGE_AT DESC);
  PRINT 'Created IX_MAIL_THREAD_LAST';
END`,
  },
  {
    name: "ZTB_MAIL_MESSAGE",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_MESSAGE')
BEGIN
  CREATE TABLE ZTB_MAIL_MESSAGE (
    ID                 INT IDENTITY(1,1) PRIMARY KEY,
    MAIL_ACCOUNT_ID    INT           NOT NULL,
    MESSAGE_ID         NVARCHAR(500) NULL,
    UIDL               NVARCHAR(200) NULL,
    THREAD_ID          INT           NULL,
    IN_REPLY_TO        NVARCHAR(500) NULL,
    REFERENCES_HEADER  NVARCHAR(MAX) NULL,
    FROM_ADDRESS       NVARCHAR(320) NULL,
    FROM_NAME          NVARCHAR(200) NULL,
    TO_JSON            NVARCHAR(MAX) NULL,
    CC_JSON            NVARCHAR(MAX) NULL,
    BCC_JSON           NVARCHAR(MAX) NULL,
    SUBJECT            NVARCHAR(500) NULL,
    SENT_AT            DATETIME2     NULL,
    RECEIVED_AT        DATETIME2     NULL,
    IS_READ            BIT           NOT NULL CONSTRAINT DF_MAIL_MSG_READ DEFAULT 0,
    IS_STARRED         BIT           NOT NULL CONSTRAINT DF_MAIL_MSG_STAR DEFAULT 0,
    IS_IMPORTANT       BIT           NOT NULL CONSTRAINT DF_MAIL_MSG_IMPORT DEFAULT 0,
    FOLDER             NVARCHAR(20)  NOT NULL CONSTRAINT DF_MAIL_MSG_FOLDER DEFAULT 'INBOX',
    HAS_ATTACHMENT     BIT           NOT NULL CONSTRAINT DF_MAIL_MSG_HASATT DEFAULT 0,
    ATTACHMENT_COUNT   INT           NOT NULL CONSTRAINT DF_MAIL_MSG_ATTN DEFAULT 0,
    BODY_STORAGE_PATH  NVARCHAR(500) NULL,
    BODY_INLINE        NVARCHAR(MAX) NULL,
    PREVIEW_TEXT       NVARCHAR(500) NULL,
    SIZE_BYTES         BIGINT        NULL,
    CONTENT_HASH       CHAR(64)      NULL,
    DELETED_AT         DATETIME2     NULL,
    CREATED_AT         DATETIME2     NOT NULL CONSTRAINT DF_MAIL_MSG_CREATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_MESSAGE';
END`,
  },
  {
    name: "UX_MAIL_MESSAGE_ID",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_MAIL_MESSAGE_ID')
BEGIN
  -- Dedup chính: 1 mailbox không thể có 2 email cùng Message-ID.
  -- Filtered vì MESSAGE_ID có thể NULL (email thiếu header) và SQL Server coi NULL là bằng nhau.
  CREATE UNIQUE INDEX UX_MAIL_MESSAGE_ID ON ZTB_MAIL_MESSAGE (MAIL_ACCOUNT_ID, MESSAGE_ID)
    WHERE MESSAGE_ID IS NOT NULL;
  PRINT 'Created UX_MAIL_MESSAGE_ID';
END`,
  },
  {
    name: "UX_MAIL_MESSAGE_UIDL",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_MAIL_MESSAGE_UIDL')
BEGIN
  CREATE UNIQUE INDEX UX_MAIL_MESSAGE_UIDL ON ZTB_MAIL_MESSAGE (MAIL_ACCOUNT_ID, UIDL)
    WHERE UIDL IS NOT NULL;
  PRINT 'Created UX_MAIL_MESSAGE_UIDL';
END`,
  },
  {
    name: "IX_MAIL_MESSAGE_INBOX",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_MESSAGE_INBOX')
BEGIN
  CREATE INDEX IX_MAIL_MESSAGE_INBOX
    ON ZTB_MAIL_MESSAGE (MAIL_ACCOUNT_ID, FOLDER, RECEIVED_AT DESC)
    INCLUDE (SUBJECT, FROM_ADDRESS, FROM_NAME, IS_READ, IS_STARRED, HAS_ATTACHMENT, ATTACHMENT_COUNT, DELETED_AT);
  PRINT 'Created IX_MAIL_MESSAGE_INBOX';
END`,
  },
  {
    name: "IX_MAIL_MESSAGE_THREAD",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_MESSAGE_THREAD')
BEGIN
  CREATE INDEX IX_MAIL_MESSAGE_THREAD ON ZTB_MAIL_MESSAGE (THREAD_ID);
  PRINT 'Created IX_MAIL_MESSAGE_THREAD';
END`,
  },
  {
    name: "IX_MAIL_MESSAGE_HASH",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_MESSAGE_HASH')
BEGIN
  CREATE INDEX IX_MAIL_MESSAGE_HASH ON ZTB_MAIL_MESSAGE (CONTENT_HASH);
  PRINT 'Created IX_MAIL_MESSAGE_HASH';
END`,
  },
  {
    name: "ZTB_MAIL_RECIPIENT",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_RECIPIENT')
BEGIN
  CREATE TABLE ZTB_MAIL_RECIPIENT (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    MESSAGE_ID      INT           NOT NULL,
    RECIPIENT_TYPE  NVARCHAR(4)   NOT NULL,   -- TO | CC | BCC
    ADDRESS         NVARCHAR(320) NOT NULL,
    DISPLAY_NAME    NVARCHAR(200) NULL
  );
  PRINT 'Created ZTB_MAIL_RECIPIENT';
END`,
  },
  {
    name: "IX_MAIL_RECIPIENT_MSG",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_RECIPIENT_MSG')
BEGIN
  CREATE INDEX IX_MAIL_RECIPIENT_MSG ON ZTB_MAIL_RECIPIENT (MESSAGE_ID, RECIPIENT_TYPE);
  PRINT 'Created IX_MAIL_RECIPIENT_MSG';
END`,
  },
  {
    name: "ZTB_MAIL_PHYSICAL_FILE",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_PHYSICAL_FILE')
BEGIN
  CREATE TABLE ZTB_MAIL_PHYSICAL_FILE (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    FILE_HASH     CHAR(64)      NOT NULL,
    STORAGE_PATH  NVARCHAR(500) NOT NULL,
    FILE_SIZE     BIGINT        NULL,
    REF_COUNT     INT           NOT NULL CONSTRAINT DF_MAIL_PFILE_REF DEFAULT 0,
    CREATED_AT    DATETIME2     NOT NULL CONSTRAINT DF_MAIL_PFILE_CREATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_PHYSICAL_FILE';
END`,
  },
  {
    name: "UX_MAIL_PHYSICAL_FILE_HASH",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_MAIL_PHYSICAL_FILE_HASH')
BEGIN
  CREATE UNIQUE INDEX UX_MAIL_PHYSICAL_FILE_HASH ON ZTB_MAIL_PHYSICAL_FILE (FILE_HASH);
  PRINT 'Created UX_MAIL_PHYSICAL_FILE_HASH';
END`,
  },
  {
    name: "ZTB_MAIL_ATTACHMENT",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_ATTACHMENT')
BEGIN
  CREATE TABLE ZTB_MAIL_ATTACHMENT (
    ID               INT IDENTITY(1,1) PRIMARY KEY,
    MESSAGE_ID       INT           NOT NULL,
    FILE_NAME        NVARCHAR(300) NULL,
    CONTENT_TYPE     NVARCHAR(150) NULL,
    FILE_SIZE        BIGINT        NULL,
    CONTENT_ID       NVARCHAR(300) NULL,
    IS_INLINE        BIT           NOT NULL CONSTRAINT DF_MAIL_ATT_INLINE DEFAULT 0,
    FILE_HASH        CHAR(64)      NULL,
    PHYSICAL_FILE_ID INT           NULL,
    STATUS           NVARCHAR(12)  NOT NULL CONSTRAINT DF_MAIL_ATT_STATUS DEFAULT 'PENDING',
    CREATED_AT       DATETIME2     NOT NULL CONSTRAINT DF_MAIL_ATT_CREATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_ATTACHMENT';
END`,
  },
  {
    name: "IX_MAIL_ATTACHMENT_MSG",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_ATTACHMENT_MSG')
BEGIN
  CREATE INDEX IX_MAIL_ATTACHMENT_MSG ON ZTB_MAIL_ATTACHMENT (MESSAGE_ID);
  PRINT 'Created IX_MAIL_ATTACHMENT_MSG';
END`,
  },
  {
    name: "IX_MAIL_ATTACHMENT_PFILE",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_ATTACHMENT_PFILE')
BEGIN
  CREATE INDEX IX_MAIL_ATTACHMENT_PFILE ON ZTB_MAIL_ATTACHMENT (PHYSICAL_FILE_ID);
  PRINT 'Created IX_MAIL_ATTACHMENT_PFILE';
END`,
  },
  {
    name: "IX_MAIL_ATTACHMENT_STATUS",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_ATTACHMENT_STATUS')
BEGIN
  CREATE INDEX IX_MAIL_ATTACHMENT_STATUS ON ZTB_MAIL_ATTACHMENT (STATUS);
  PRINT 'Created IX_MAIL_ATTACHMENT_STATUS';
END`,
  },
  {
    name: "ZTB_MAIL_USERSTATE",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_USERSTATE')
BEGIN
  CREATE TABLE ZTB_MAIL_USERSTATE (
    MESSAGE_ID      INT           NOT NULL,
    EMPL_NO         NVARCHAR(20)  NOT NULL,
    IS_READ         BIT           NOT NULL CONSTRAINT DF_MAIL_US_READ DEFAULT 0,
    IS_STARRED      BIT           NOT NULL CONSTRAINT DF_MAIL_US_STAR DEFAULT 0,
    IS_IMPORTANT    BIT           NOT NULL CONSTRAINT DF_MAIL_US_IMPORT DEFAULT 0,
    READ_AT         DATETIME2     NULL,
    FOLDER_OVERRIDE NVARCHAR(20)  NULL,
    DELETED_AT      DATETIME2     NULL,
    CREATED_AT      DATETIME2     NOT NULL CONSTRAINT DF_MAIL_US_CREATED DEFAULT GETDATE(),
    UPDATED_AT      DATETIME2     NOT NULL CONSTRAINT DF_MAIL_US_UPDATED DEFAULT GETDATE(),
    CONSTRAINT PK_MAIL_USERSTATE PRIMARY KEY (MESSAGE_ID, EMPL_NO)
  );
  PRINT 'Created ZTB_MAIL_USERSTATE';
END`,
  },
  {
    name: "IX_MAIL_USERSTATE_EMPL",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_USERSTATE_EMPL')
BEGIN
  CREATE INDEX IX_MAIL_USERSTATE_EMPL ON ZTB_MAIL_USERSTATE (EMPL_NO, IS_READ, DELETED_AT);
  PRINT 'Created IX_MAIL_USERSTATE_EMPL';
END`,
  },
  {
    name: "ZTB_MAIL_FOLDER",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_FOLDER')
BEGIN
  CREATE TABLE ZTB_MAIL_FOLDER (
    ID           INT IDENTITY(1,1) PRIMARY KEY,
    CTR_CD       NVARCHAR(20)  NOT NULL,
    EMPL_NO      NVARCHAR(20)  NOT NULL CONSTRAINT DF_MAIL_FOLDER_EMPL DEFAULT '',
    FOLDER_KEY   NVARCHAR(40)  NOT NULL,
    DISPLAY_NAME NVARCHAR(100) NULL,
    SORT_ORDER   INT           NOT NULL CONSTRAINT DF_MAIL_FOLDER_ORDER DEFAULT 0,
    IS_SYSTEM    BIT           NOT NULL CONSTRAINT DF_MAIL_FOLDER_SYS DEFAULT 0,
    CREATED_AT   DATETIME2     NOT NULL CONSTRAINT DF_MAIL_FOLDER_CREATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_FOLDER';
END`,
  },
  {
    name: "UX_MAIL_FOLDER_KEY",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_MAIL_FOLDER_KEY')
BEGIN
  CREATE UNIQUE INDEX UX_MAIL_FOLDER_KEY ON ZTB_MAIL_FOLDER (CTR_CD, EMPL_NO, FOLDER_KEY);
  PRINT 'Created UX_MAIL_FOLDER_KEY';
END`,
  },
  {
    name: "ZTB_MAIL_DRAFT",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_DRAFT')
BEGIN
  CREATE TABLE ZTB_MAIL_DRAFT (
    ID               INT IDENTITY(1,1) PRIMARY KEY,
    CTR_CD           NVARCHAR(20)  NOT NULL,
    EMPL_NO          NVARCHAR(20)  NOT NULL,
    TO_JSON          NVARCHAR(MAX) NULL,
    CC_JSON          NVARCHAR(MAX) NULL,
    BCC_JSON         NVARCHAR(MAX) NULL,
    SUBJECT          NVARCHAR(500) NULL,
    BODY_HTML        NVARCHAR(MAX) NULL,
    BODY_TEXT        NVARCHAR(MAX) NULL,
    ATTACH_JSON      NVARCHAR(MAX) NULL,
    IN_REPLY_TO      NVARCHAR(500) NULL,
    REFERENCES_HEADER NVARCHAR(MAX) NULL,
    CREATED_AT       DATETIME2     NOT NULL CONSTRAINT DF_MAIL_DRAFT_CREATED DEFAULT GETDATE(),
    UPDATED_AT       DATETIME2     NOT NULL CONSTRAINT DF_MAIL_DRAFT_UPDATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_DRAFT';
END`,
  },
  {
    name: "IX_MAIL_DRAFT_EMPL",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_DRAFT_EMPL')
BEGIN
  CREATE INDEX IX_MAIL_DRAFT_EMPL ON ZTB_MAIL_DRAFT (EMPL_NO, UPDATED_AT DESC);
  PRINT 'Created IX_MAIL_DRAFT_EMPL';
END`,
  },
  {
    name: "ZTB_MAIL_SYNC_LOG",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_SYNC_LOG')
BEGIN
  CREATE TABLE ZTB_MAIL_SYNC_LOG (
    ID               INT IDENTITY(1,1) PRIMARY KEY,
    MAIL_ACCOUNT_ID  INT           NOT NULL,
    STARTED_AT       DATETIME2     NOT NULL CONSTRAINT DF_MAIL_LOG_STARTED DEFAULT GETDATE(),
    FINISHED_AT      DATETIME2     NULL,
    STATUS           NVARCHAR(20)  NULL,
    CONNECTED        BIT           NOT NULL CONSTRAINT DF_MAIL_LOG_CONN DEFAULT 0,
    NEW_COUNT        INT           NOT NULL CONSTRAINT DF_MAIL_LOG_NEW DEFAULT 0,
    IMPORTED_COUNT   INT           NOT NULL CONSTRAINT DF_MAIL_LOG_IMP DEFAULT 0,
    ATTACH_COUNT     INT           NOT NULL CONSTRAINT DF_MAIL_LOG_ATT DEFAULT 0,
    ERROR_CODE       NVARCHAR(40)  NULL,
    ERROR_MESSAGE    NVARCHAR(1000) NULL,
    DURATION_MS      INT           NULL
  );
  PRINT 'Created ZTB_MAIL_SYNC_LOG';
END`,
  },
  {
    name: "IX_MAIL_SYNC_LOG_ACC",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_SYNC_LOG_ACC')
BEGIN
  CREATE INDEX IX_MAIL_SYNC_LOG_ACC ON ZTB_MAIL_SYNC_LOG (MAIL_ACCOUNT_ID, STARTED_AT DESC);
  PRINT 'Created IX_MAIL_SYNC_LOG_ACC';
END`,
  },
  {
    name: "ZTB_MAIL_SYNC_CHECKPOINT",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_SYNC_CHECKPOINT')
BEGIN
  CREATE TABLE ZTB_MAIL_SYNC_CHECKPOINT (
    MAIL_ACCOUNT_ID  INT           NOT NULL PRIMARY KEY,
    LAST_UIDL        NVARCHAR(200) NULL,
    LAST_SYNC_AT     DATETIME2     NULL,
    IN_PROGRESS      BIT           NOT NULL CONSTRAINT DF_MAIL_CKPT_INPROG DEFAULT 0,
    LOCKED_AT        DATETIME2     NULL,
    LOCKED_BY        NVARCHAR(100) NULL,
    TOTAL_IMPORTED   INT           NOT NULL CONSTRAINT DF_MAIL_CKPT_TOTAL DEFAULT 0
  );
  PRINT 'Created ZTB_MAIL_SYNC_CHECKPOINT';
END`,
  },
  {
    name: "IX_MAIL_ACCOUNT_EMPL",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_ACCOUNT_EMPL')
BEGIN
  -- Tăng tốc tra mailbox RIÊNG theo nhân sự (self-service) + liệt kê theo công ty.
  CREATE INDEX IX_MAIL_ACCOUNT_EMPL ON ZTB_MAIL_ACCOUNT (CTR_CD, EMPL_NO, IS_ACTIVE);
  PRINT 'Created IX_MAIL_ACCOUNT_EMPL';
END`,
  },
  {
    name: "ZTB_MAIL_SYNC_CHECKPOINT.SERVER_TOTAL",
    sql: `IF NOT EXISTS (
       SELECT * FROM sys.columns
       WHERE object_id = OBJECT_ID('ZTB_MAIL_SYNC_CHECKPOINT') AND name = 'SERVER_TOTAL')
BEGIN
  -- Tổng số email báo bởi POP3 STAT ở lần đồng bộ gần nhất (để hiển thị tiến độ).
  ALTER TABLE ZTB_MAIL_SYNC_CHECKPOINT ADD SERVER_TOTAL INT NULL;
  PRINT 'Added SERVER_TOTAL';
END`,
  },
  {
    name: "ZTB_MAIL_OUTBOX",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_OUTBOX')
BEGIN
  -- Tệp đính kèm SOẠN THẢO: upload trước khi gửi (chưa gắn vào email nào).
  CREATE TABLE ZTB_MAIL_OUTBOX (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CTR_CD        NVARCHAR(20)  NOT NULL,
    EMPL_NO       NVARCHAR(20)  NOT NULL,
    FILE_NAME     NVARCHAR(300) NULL,
    CONTENT_TYPE  NVARCHAR(150) NULL,
    FILE_SIZE     BIGINT        NULL,
    STORAGE_PATH  NVARCHAR(500) NOT NULL,
    CREATED_AT    DATETIME2     NOT NULL CONSTRAINT DF_MAIL_OUTBOX_CREATED DEFAULT GETDATE()
  );
  PRINT 'Created ZTB_MAIL_OUTBOX';
END`,
  },
  {
    name: "IX_MAIL_OUTBOX_EMPL",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MAIL_OUTBOX_EMPL')
BEGIN
  CREATE INDEX IX_MAIL_OUTBOX_EMPL ON ZTB_MAIL_OUTBOX (EMPL_NO, CREATED_AT DESC);
  PRINT 'Created IX_MAIL_OUTBOX_EMPL';
END`,
  },
  {
    // Phase 7 — tắt/bật thông báo đẩy THEO TỪNG NGƯỜI cho từng mailbox (mailbox dùng chung vẫn tách riêng được).
    name: "ZTB_MAIL_MUTE",
    sql: `IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ZTB_MAIL_MUTE')
BEGIN
  CREATE TABLE ZTB_MAIL_MUTE (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    CTR_CD          NVARCHAR(20) NOT NULL,
    EMPL_NO         NVARCHAR(20) NOT NULL,
    MAIL_ACCOUNT_ID INT          NOT NULL,
    CREATED_AT      DATETIME2    NOT NULL CONSTRAINT DF_MAIL_MUTE_CREATED DEFAULT GETDATE(),
    CONSTRAINT FK_MAIL_MUTE_ACCOUNT FOREIGN KEY (MAIL_ACCOUNT_ID) REFERENCES ZTB_MAIL_ACCOUNT (ID)
  );
  PRINT 'Created ZTB_MAIL_MUTE';
END`,
  },
  {
    name: "UX_MAIL_MUTE",
    sql: `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_MAIL_MUTE')
BEGIN
  CREATE UNIQUE INDEX UX_MAIL_MUTE ON ZTB_MAIL_MUTE (EMPL_NO, MAIL_ACCOUNT_ID);
  PRINT 'Created UX_MAIL_MUTE';
END`,
  },
];

async function main() {
  const connection = await openConnection();
  try {
    for (const statement of STATEMENTS) {
      try {
        await connection.query(statement.sql);
        console.log(`[migrate] OK  — ${statement.name}`);
      } catch (error) {
        console.error(`[migrate] LỖI — ${statement.name}: ${error.message}`);
        throw error;
      }
    }
    console.log("[migrate] Hoàn tất migrate_mail_tables.js");
  } finally {
    try {
      await connection.close();
    } catch {
      /* bỏ qua */
    }
  }
}

main().catch((error) => {
  console.error("[migrate] Thất bại:", error);
  process.exit(1);
});
